### PR TITLE
convert gradle to maven - WIP

### PR DESCRIPTION
**Pull request by JerryShea**

### CODE REVIEW

**Comment by JerryShea** [comment]
@minborg this is not working yet but better than trying to use gradle 3

**Comment by JerryShea** [comment]
I see
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project stage-compiler: Compilation failure
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider net.openhft.sg.ContextProcessor not found
```
If I remove the `javax.annotation.processing.Processor` file, build, then re-add it then the everything builds OK

**Review by minborg — APPROVED** [review]
Great.

**Comment by minborg** [comment]
This works under IDEA but not under Maven:

```
[INFO] Running net.openhft.sg.ParametersFieldsNameCollisionTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.61 s <<< FAILURE! - in net.openhft.sg.ParametersFieldsNameCollisionTest
[ERROR] net.openhft.sg.ParametersFieldsNameCollisionTest.testParametersFieldsNameCollision  Time elapsed: 0.562 s  <<< ERROR!
java.lang.RuntimeException: org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files
	at net.openhft.sg.ParametersFieldsNameCollisionTest.getFactoryForTest(ParametersFieldsNameCollisionTest.java:36)
	at net.openhft.sg.ParametersFieldsNameCollisionTest.testParametersFieldsNameCollision(ParametersFieldsNameCollisionTest.java:43)
Caused by: org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files
	at net.openhft.sg.ParametersFieldsNameCollisionTest.getFactoryForTest(ParametersFieldsNameCollisionTest.java:34)
	at net.openhft.sg.ParametersFieldsNameCollisionTest.testParametersFieldsNameCollision(ParametersFieldsNameCollisionTest.java:43)

... MORE ERRORS

```

**Pull request merged**
